apiVersion: v1
kind: ConfigMap
metadata:
  name: feast-config
  namespace: mlops-feast
data:
  feature_store.yaml: |
    project: mlops_platform
    registry:
      registry_type: sql
      path: postgresql://feast:feastpassword@postgresql.mlops-infra.svc.cluster.local:5432/feast
    provider: local
    online_store:
      type: redis
      connection_string: "redis-master.mlops-feast.svc.cluster.local:6379,db=0"
    offline_store:
      type: file
    entity_key_serialization_version: 2