images:
  airflow:
    repository: saoudyahya/airflow-dvc
    tag: latest
    pullPolicy: Always

executor: KubernetesExecutor

webserver:
  webserverSecretKey: "5a887a837794b679764eae82e0c19cffce67a3496b346dba84feb26b41bf392a"

dags:
  gitSync:
    enabled: true
    repo: https://github.com/Saoudyahya/Saoudyahya-On-Premise-MLOps-Platform-Argocd
    branch: main
    subPath: dags/
    wait: 60
    uid: 65533

env:
  - name: MLFLOW_TRACKING_URI
    value: http://mlflow-svc.mlops-mlflow.svc.cluster.local:5000
  - name: AIRFLOW__CORE__LOAD_EXAMPLES
    value: "False"

secret:
  - envName: AIRFLOW__CORE__FERNET_KEY
    secretName: airflow-fernet-key
    secretKey: fernet-key

postgresql:
  enabled: true
  auth:
    username: airflow
    password: airflow-password
    database: airflow

redis:
  enabled: false

workers:
  replicas: 0

ingress:
  web:
    enabled: true
    ingressClassName: nginx
    hosts:
      - name: airflow.yourdomain.com
        tls:
          enabled: false