apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: mlops-mlflow
  labels:
    app: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: mlflow
          image: ghcr.io/mlflow/mlflow:v2.11.0
          command:
            - sh
            - -c
            - |
              pip install psycopg2-binary flask-login --quiet && \
              python -m mlflow.server.auth db upgrade \
                --url postgresql://mlflow:mlflow-password@mlflow-postgresql-svc.mlops-mlflow.svc.cluster.local:5432/mlflow?sslmode=disable && \
              mlflow server \
                --backend-store-uri=$(MLFLOW_BACKEND_STORE_URI) \
                --default-artifact-root=$(MLFLOW_ARTIFACT_ROOT) \
                --host=0.0.0.0 \
                --port=5000 \
                --app-name basic-auth \
                --workers 1
          ports:
            - containerPort: 5000
              name: http
          env:
            - name: MLFLOW_BACKEND_STORE_URI
              value: postgresql://mlflow:mlflow-password@mlflow-postgresql-svc.mlops-mlflow.svc.cluster.local:5432/mlflow?sslmode=disable
            - name: MLFLOW_ARTIFACT_ROOT
              value: s3://mlops-mlflow/
            - name: AWS_ENDPOINT_URL
              value: http://minio-svc.mlops-minio.svc.cluster.local:9000
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: root-user
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: root-password
            - name: MLFLOW_S3_ENDPOINT_URL
              value: http://minio-svc.mlops-minio.svc.cluster.local:9000
            - name: MLFLOW_AUTH_CONFIG_PATH
              value: /etc/mlflow/auth.ini
          volumeMounts:
            - name: auth-config
              mountPath: /etc/mlflow
      volumes:
        - name: auth-config
          configMap:
            name: mlflow-auth-config