apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-postgresql
  namespace: mlops-mlflow
  labels:
    app: mlflow-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-postgresql
  template:
    metadata:
      labels:
        app: mlflow-postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: mlflow
            - name: POSTGRES_USER
              value: mlflow
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mlflow-postgresql-secret
                  key: postgres-password
            - name: POSTGRES_HOST_AUTH_METHOD
              value: md5
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mlflow-postgresql-pvc