apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-postgresql-pvc
  namespace: mlops-mlflow
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi