apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyterhub
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://hub.jupyter.org/helm-chart/
      chart: jupyterhub
      targetRevision: 3.3.7
      helm:
        valueFiles:
          - $values/jupyterhub/values.yaml
    - repoURL: https://github.com/Saoudyahya/Saoudyahya-On-Premise-MLOps-Platform-Argocd/
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: mlops-jupyterhub
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true