apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ray
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Saoudyahya/Saoudyahya-On-Premise-MLOps-Platform-Argocd/
    targetRevision: main
    path: ray/
  destination:
    server: https://kubernetes.default.svc
    namespace: mlops-ray
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true