apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: um6p-shared-datasets
  namespace: mlops-jupyterhub
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: rook-ceph-cephfs
  resources:
    requests:
      storage: 5Gi
